<?php

namespace Database\Seeders;

use App\Models\Game;
use Illuminate\Database\Seeder;

/**
 * All embed_urls use GameDistribution (html5.gamedistribution.com)
 * which explicitly allows third-party iframe embedding.
 * Format: https://html5.gamedistribution.com/{32-char-hash}/
 */
class GameSeeder extends Seeder
{
    public function run(): void
    {
        Game::truncate();
        $games = [

            // ── Puzzle (10) ──────────────────────────────────────────────────
            [
                'title'       => 'Minesweeper Classic',
                'description' => 'The classic old-fashioned minesweeper. Flag all mines without triggering any — pure logic under pressure.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://html5.gamedistribution.com/ca99b316e5924c50aed1c7d9fc756934/',
                'thumbnail'   => 'https://img.gamedistribution.com/ca99b316e5924c50aed1c7d9fc756934-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 820,
                'tags'        => ['minesweeper', 'classic', 'logic'],
            ],
            [
                'title'       => 'Microsoft Minesweeper',
                'description' => 'The reimagined Windows classic with updated graphics. Mark all mine locations without uncovering any.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://html5.gamedistribution.com/fcc8df3c59264091988cf362480ae62d/',
                'thumbnail'   => 'https://img.gamedistribution.com/fcc8df3c59264091988cf362480ae62d-512x384.jpeg',
                'is_featured' => true,
                'plays'       => 1200,
                'tags'        => ['minesweeper', 'microsoft', 'logic'],
            ],
            [
                'title'       => 'Chess',
                'description' => 'Play chess against a smart AI. Multiple difficulty levels from beginner to grandmaster.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://html5.gamedistribution.com/fc4c8e3b7bfc4e7da7e72e7769ee4e97/',
                'thumbnail'   => 'https://img.gamedistribution.com/fc4c8e3b7bfc4e7da7e72e7769ee4e97-512x384.jpeg',
                'is_featured' => true,
                'plays'       => 2100,
                'tags'        => ['chess', 'board', 'ai'],
            ],
            [
                'title'       => '2048',
                'description' => 'Slide tiles on a grid to combine numbers and reach the 2048 tile. Highly addictive.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://html5.gamedistribution.com/7258d1e51bd74f60901da63c4dd1d594/',
                'thumbnail'   => 'https://img.gamedistribution.com/7258d1e51bd74f60901da63c4dd1d594-512x384.jpeg',
                'is_featured' => true,
                'plays'       => 1240,
                'tags'        => ['2048', 'numbers', 'casual'],
            ],
            [
                'title'       => 'Sudoku Classic',
                'description' => 'Fill the 9×9 grid so every row, column, and box contains digits 1–9.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://html5.gamedistribution.com/5de53c3b62d24b1d8a8c2609000fd79c/',
                'thumbnail'   => 'https://img.gamedistribution.com/5de53c3b62d24b1d8a8c2609000fd79c-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 540,
                'tags'        => ['sudoku', 'numbers', 'logic'],
            ],
            [
                'title'       => 'Mahjong Classic',
                'description' => 'Match and remove pairs of tiles to clear the board in this timeless solitaire classic.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://html5.gamedistribution.com/fcf7e54735634e11bfe16e84d9f8f5a5/',
                'thumbnail'   => 'https://img.gamedistribution.com/fcf7e54735634e11bfe16e84d9f8f5a5-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 390,
                'tags'        => ['mahjong', 'tiles', 'classic'],
            ],
            [
                'title'       => 'Classic Solitaire',
                'description' => 'The timeless card game. Stack all cards onto four foundation piles to win.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://html5.gamedistribution.com/61a7de6db3954f0096de4007d3555bef/',
                'thumbnail'   => 'https://img.gamedistribution.com/61a7de6db3954f0096de4007d3555bef-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 1340,
                'tags'        => ['solitaire', 'cards', 'classic'],
            ],
            [
                'title'       => 'Spider Solitaire',
                'description' => 'Build eight complete suits from King to Ace to clear the tableau.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://html5.gamedistribution.com/b30803e84e4c45a5ab4bc7e0b0b46d24/',
                'thumbnail'   => 'https://img.gamedistribution.com/b30803e84e4c45a5ab4bc7e0b0b46d24-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 980,
                'tags'        => ['solitaire', 'cards', 'spider'],
            ],
            [
                'title'       => 'Bubble Shooter',
                'description' => 'Aim and shoot coloured bubbles to pop matching groups of three or more.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://html5.gamedistribution.com/46b8f9f9d14c4f0ba89eea29a8d86498/',
                'thumbnail'   => 'https://img.gamedistribution.com/46b8f9f9d14c4f0ba89eea29a8d86498-512x384.jpeg',
                'is_featured' => true,
                'plays'       => 1950,
                'tags'        => ['bubbles', 'shooter', 'match3'],
            ],
            [
                'title'       => 'Cut the Rope',
                'description' => 'Slice ropes at just the right moment to feed candy to the little monster Om Nom.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://html5.gamedistribution.com/b23a4f4c55e5476398ef498aaeba8cf2/',
                'thumbnail'   => 'https://img.gamedistribution.com/b23a4f4c55e5476398ef498aaeba8cf2-512x384.jpeg',
                'is_featured' => true,
                'plays'       => 1680,
                'tags'        => ['rope', 'physics', 'casual'],
            ],

            // ── Arcade (10) ──────────────────────────────────────────────────
            [
                'title'       => 'Pac-Man',
                'description' => 'Chomp dots and dodge ghosts in the iconic golden-age arcade maze.',
                'category'    => 'arcade',
                'embed_url'   => 'https://html5.gamedistribution.com/c1ab0765d7bd4fbfb823f6022a5c26ee/',
                'thumbnail'   => 'https://img.gamedistribution.com/c1ab0765d7bd4fbfb823f6022a5c26ee-512x384.jpeg',
                'is_featured' => true,
                'plays'       => 4200,
                'tags'        => ['pacman', 'maze', 'classic'],
            ],
            [
                'title'       => 'Tetris',
                'description' => 'The classic block-stacking game. Clear lines before the stack reaches the top.',
                'category'    => 'arcade',
                'embed_url'   => 'https://html5.gamedistribution.com/e83975cf657c43c8b4a8b4fdc1b11ebe/',
                'thumbnail'   => 'https://img.gamedistribution.com/e83975cf657c43c8b4a8b4fdc1b11ebe-512x384.jpeg',
                'is_featured' => true,
                'plays'       => 3890,
                'tags'        => ['tetris', 'blocks', 'classic'],
            ],
            [
                'title'       => 'Snake',
                'description' => 'Guide the snake to eat food and grow — without hitting the walls or yourself.',
                'category'    => 'arcade',
                'embed_url'   => 'https://html5.gamedistribution.com/a9e01b1f09534b92a2f0e1cff88e82e7/',
                'thumbnail'   => 'https://img.gamedistribution.com/a9e01b1f09534b92a2f0e1cff88e82e7-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 710,
                'tags'        => ['snake', 'classic', 'retro'],
            ],
            [
                'title'       => 'Fruit Ninja',
                'description' => 'Slice flying fruit with your blade — but never hit a bomb.',
                'category'    => 'arcade',
                'embed_url'   => 'https://html5.gamedistribution.com/7aaed27d2f9b43518c13f14b6c0d22de/',
                'thumbnail'   => 'https://img.gamedistribution.com/7aaed27d2f9b43518c13f14b6c0d22de-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 1100,
                'tags'        => ['fruit', 'slice', 'reflex'],
            ],
            [
                'title'       => 'Helix Jump',
                'description' => 'Bounce the ball down the helix tower by rotating the platforms to avoid the dark gaps.',
                'category'    => 'arcade',
                'embed_url'   => 'https://html5.gamedistribution.com/e0cb657044924a71aa95b3dcd8e66a98/',
                'thumbnail'   => 'https://img.gamedistribution.com/e0cb657044924a71aa95b3dcd8e66a98-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 1350,
                'tags'        => ['helix', 'ball', 'casual'],
            ],
            [
                'title'       => 'Knife Hit',
                'description' => 'Throw knives at rotating logs without hitting other knives already stuck in.',
                'category'    => 'arcade',
                'embed_url'   => 'https://html5.gamedistribution.com/af0b65a72e074a93b6b5ce94e7ee8ec8/',
                'thumbnail'   => 'https://img.gamedistribution.com/af0b65a72e074a93b6b5ce94e7ee8ec8-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 1200,
                'tags'        => ['knife', 'aim', 'casual'],
            ],
            [
                'title'       => 'Crossy Road',
                'description' => 'Hop your chicken across endless roads, rivers, and rails without getting squished.',
                'category'    => 'arcade',
                'embed_url'   => 'https://html5.gamedistribution.com/rvvASMiM/406c04f585a04a50aab1572f4e852b06/',
                'thumbnail'   => 'https://img.gamedistribution.com/406c04f585a04a50aab1572f4e852b06-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 1100,
                'tags'        => ['chicken', 'hop', 'endless'],
            ],
            [
                'title'       => 'Jetpack Joyride',
                'description' => 'Fly a jetpack through a lab packed with lasers, zappers, and missiles.',
                'category'    => 'arcade',
                'embed_url'   => 'https://html5.gamedistribution.com/3dba5c67f19742d1b5ff5f3baf1b1a78/',
                'thumbnail'   => 'https://img.gamedistribution.com/3dba5c67f19742d1b5ff5f3baf1b1a78-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 1450,
                'tags'        => ['jetpack', 'runner', 'endless'],
            ],
            [
                'title'       => 'Piano Tiles',
                'description' => 'Tap the black tiles to the beat — never miss or tap white tiles.',
                'category'    => 'arcade',
                'embed_url'   => 'https://html5.gamedistribution.com/c52f2d7de7b040918c877a00db6eb7c0/',
                'thumbnail'   => 'https://img.gamedistribution.com/c52f2d7de7b040918c877a00db6eb7c0-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 1580,
                'tags'        => ['music', 'tap', 'reflex'],
            ],
            [
                'title'       => 'Color Switch',
                'description' => 'Pass the ball through spinning colour obstacles — only matching sections let you through.',
                'category'    => 'arcade',
                'embed_url'   => 'https://html5.gamedistribution.com/d9b7da0e12544cf5a4dbab3d9e49e9b0/',
                'thumbnail'   => 'https://img.gamedistribution.com/d9b7da0e12544cf5a4dbab3d9e49e9b0-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 780,
                'tags'        => ['color', 'reflex', 'casual'],
            ],

            // ── Action (6) ───────────────────────────────────────────────────
            [
                'title'       => 'Stickman Hook',
                'description' => 'Swing through levels on a grappling hook in this satisfying physics platformer.',
                'category'    => 'action',
                'embed_url'   => 'https://html5.gamedistribution.com/6134e22e5a5b40e0baf9e0c4a49f8d65/',
                'thumbnail'   => 'https://img.gamedistribution.com/6134e22e5a5b40e0baf9e0c4a49f8d65-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 940,
                'tags'        => ['stickman', 'swing', 'physics'],
            ],
            [
                'title'       => 'Rooftop Snipers',
                'description' => 'Two players battle on rooftops — knock your opponent off the edge to score.',
                'category'    => 'action',
                'embed_url'   => 'https://html5.gamedistribution.com/c27cdcf8c86e41aeb9a27949a60f89d3/',
                'thumbnail'   => 'https://img.gamedistribution.com/c27cdcf8c86e41aeb9a27949a60f89d3-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 1340,
                'tags'        => ['sniper', 'two-player', 'funny'],
            ],
            [
                'title'       => 'Getaway Shootout',
                'description' => 'Leap and scramble to the getaway vehicle before your opponents do.',
                'category'    => 'action',
                'embed_url'   => 'https://html5.gamedistribution.com/79e9a9f430094ef6a3d11a0a8e7793cb/',
                'thumbnail'   => 'https://img.gamedistribution.com/79e9a9f430094ef6a3d11a0a8e7793cb-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 1180,
                'tags'        => ['getaway', 'two-player', 'funny'],
            ],
            [
                'title'       => 'Happy Wheels',
                'description' => 'Race ragdoll characters through gory obstacle courses in a chaotic physics game.',
                'category'    => 'action',
                'embed_url'   => 'https://html5.gamedistribution.com/a92745059e14453db6dc6b4b8d5d1afa/',
                'thumbnail'   => 'https://img.gamedistribution.com/a92745059e14453db6dc6b4b8d5d1afa-512x384.jpeg',
                'is_featured' => true,
                'plays'       => 2900,
                'tags'        => ['ragdoll', 'physics', 'funny'],
            ],
            [
                'title'       => 'Iron Snout',
                'description' => 'Control a pig doing martial-arts combos to smash relentless incoming wolves.',
                'category'    => 'action',
                'embed_url'   => 'https://html5.gamedistribution.com/9b49f4f3d50945b5a73b9c8b7f6bb48d/',
                'thumbnail'   => 'https://img.gamedistribution.com/9b49f4f3d50945b5a73b9c8b7f6bb48d-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 590,
                'tags'        => ['fighting', 'pig', 'funny'],
            ],
            [
                'title'       => 'Bowman',
                'description' => 'Draw your bowstring and release at the right angle to hit the rival archer.',
                'category'    => 'action',
                'embed_url'   => 'https://html5.gamedistribution.com/3ba15f48cf584bdf9bb8c5d0c5d24c5f/',
                'thumbnail'   => 'https://img.gamedistribution.com/3ba15f48cf584bdf9bb8c5d0c5d24c5f-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 560,
                'tags'        => ['bow', 'aim', 'two-player'],
            ],

            // ── Racing (6) ───────────────────────────────────────────────────
            [
                'title'       => 'Moto X3M',
                'description' => 'Race a dirt bike through wild obstacle courses packed with explosions and loops.',
                'category'    => 'racing',
                'embed_url'   => 'https://html5.gamedistribution.com/b7f09e1f55ef4db1a12f5a8f5a8de3c6/',
                'thumbnail'   => 'https://img.gamedistribution.com/b7f09e1f55ef4db1a12f5a8f5a8de3c6-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 1560,
                'tags'        => ['bike', 'stunts', 'obstacles'],
            ],
            [
                'title'       => 'Drift Hunters',
                'description' => 'Earn points by drifting tuned cars around technical courses. Upgrade your ride.',
                'category'    => 'racing',
                'embed_url'   => 'https://html5.gamedistribution.com/2eb9e3893e4e42aba938c4dab5e74a3a/',
                'thumbnail'   => 'https://img.gamedistribution.com/2eb9e3893e4e42aba938c4dab5e74a3a-512x384.jpeg',
                'is_featured' => true,
                'plays'       => 1980,
                'tags'        => ['drift', 'cars', 'tuning'],
            ],
            [
                'title'       => 'Hill Climb Racing',
                'description' => 'Gun the engine and conquer hilly terrain without flipping your vehicle.',
                'category'    => 'racing',
                'embed_url'   => 'https://html5.gamedistribution.com/f1bb88c9b5354e2383ac3ab99e2dd900/',
                'thumbnail'   => 'https://img.gamedistribution.com/f1bb88c9b5354e2383ac3ab99e2dd900-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 1390,
                'tags'        => ['hill', 'climb', 'physics'],
            ],
            [
                'title'       => 'Traffic Jam 3D',
                'description' => 'Weave through packed highways without crashing in hypnotic 3D traffic.',
                'category'    => 'racing',
                'embed_url'   => 'https://html5.gamedistribution.com/6ba4d6e2e47940d285a69a43c2dc0ea2/',
                'thumbnail'   => 'https://img.gamedistribution.com/6ba4d6e2e47940d285a69a43c2dc0ea2-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 640,
                'tags'        => ['traffic', '3d', 'endless'],
            ],
            [
                'title'       => 'Moto X3M Pool Party',
                'description' => 'Race your motorbike through pool floats, water slides, and summer obstacles.',
                'category'    => 'racing',
                'embed_url'   => 'https://html5.gamedistribution.com/b13f7396e77a4f6d92f9e8f5bf0bc5c4/',
                'thumbnail'   => 'https://img.gamedistribution.com/b13f7396e77a4f6d92f9e8f5bf0bc5c4-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 1080,
                'tags'        => ['bike', 'pool', 'obstacles'],
            ],


            // ── Sports (9) ───────────────────────────────────────────────────
            [
                'title'       => 'Basketball Stars',
                'description' => 'Show off ball-handling tricks and score slick buckets in arcade basketball.',
                'category'    => 'sports',
                'embed_url'   => 'https://html5.gamedistribution.com/20ea5b34d7cf4a94be0898aced25f9f9/',
                'thumbnail'   => 'https://img.gamedistribution.com/20ea5b34d7cf4a94be0898aced25f9f9-512x384.jpeg',
                'is_featured' => true,
                'plays'       => 1870,
                'tags'        => ['basketball', 'tricks', 'arcade'],
            ],
            [
                'title'       => 'Penalty Shooters 2',
                'description' => 'Take and save penalties across a tournament bracket to lift the trophy.',
                'category'    => 'sports',
                'embed_url'   => 'https://html5.gamedistribution.com/0dca55ded33e4d7db5cf7fe3f50dafb6/',
                'thumbnail'   => 'https://img.gamedistribution.com/0dca55ded33e4d7db5cf7fe3f50dafb6-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 930,
                'tags'        => ['soccer', 'penalty', 'tournament'],
            ],
            [
                'title'       => 'Soccer Random',
                'description' => 'Physics chaos soccer — controls and conditions change every round.',
                'category'    => 'sports',
                'embed_url'   => 'https://html5.gamedistribution.com/7d1a78e64fc54b0b9e6af7e24a72c72b/',
                'thumbnail'   => 'https://img.gamedistribution.com/7d1a78e64fc54b0b9e6af7e24a72c72b-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 1450,
                'tags'        => ['soccer', 'random', 'funny'],
            ],

            [
                'title'       => 'Penalty Kick Online',
                'description' => 'Strike and save penalties against players from around the world.',
                'category'    => 'sports',
                'embed_url'   => 'https://html5.gamedistribution.com/4a5a5d84f4e14fcfa39d6fee1c9e8de5/',
                'thumbnail'   => 'https://img.gamedistribution.com/4a5a5d84f4e14fcfa39d6fee1c9e8de5-512x384.jpeg',
                'is_featured' => true,
                'plays'       => 2100,
                'tags'        => ['soccer', 'penalty', 'online'],
            ],
            [
                'title'       => 'Pool Billiards Pro',
                'description' => 'Pot balls in the correct order in this smooth 8-ball billiards game.',
                'category'    => 'sports',
                'embed_url'   => 'https://html5.gamedistribution.com/3e62afb3c8764a17af82fe2e2e918b7b/',
                'thumbnail'   => 'https://img.gamedistribution.com/3e62afb3c8764a17af82fe2e2e918b7b-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 780,
                'tags'        => ['pool', 'billiards', 'classic'],
            ],
            [
                'title'       => 'Archery World Tour',
                'description' => 'Aim carefully and account for wind to hit bullseyes on exotic world stages.',
                'category'    => 'sports',
                'embed_url'   => 'https://html5.gamedistribution.com/rvvASMiM/1cabb62e97824ed485f17b97a3e5e1ad/',
                'thumbnail'   => 'https://img.gamedistribution.com/1cabb62e97824ed485f17b97a3e5e1ad-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 640,
                'tags'        => ['archery', 'aim', 'tournament'],
            ],

            [
                'title'       => 'Head Soccer',
                'description' => '1-v-1 soccer with oversized heads — score more goals before the clock runs out.',
                'category'    => 'sports',
                'embed_url'   => 'https://html5.gamedistribution.com/0c8fd76b629d48e9aef8a72e7eb40e4f/',
                'thumbnail'   => 'https://img.gamedistribution.com/0c8fd76b629d48e9aef8a72e7eb40e4f-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 1100,
                'tags'        => ['soccer', 'heads', 'two-player'],
            ],

            // ── Adventure (6) ────────────────────────────────────────────────
            [
                'title'       => 'Fireboy and Watergirl: Forest Temple',
                'description' => 'Co-op puzzle platformer — use each character\'s element to unlock new paths.',
                'category'    => 'adventure',
                'embed_url'   => 'https://html5.gamedistribution.com/d6cb94dde81a4fa6b0e6bd55aa60a16e/',
                'thumbnail'   => 'https://img.gamedistribution.com/d6cb94dde81a4fa6b0e6bd55aa60a16e-512x384.jpeg',
                'is_featured' => true,
                'plays'       => 3050,
                'tags'        => ['co-op', 'puzzle', 'platformer'],
            ],
            [
                'title'       => 'Slope',
                'description' => 'Steer a speeding ball down an infinite neon slope — don\'t fly off the edges.',
                'category'    => 'adventure',
                'embed_url'   => 'https://html5.gamedistribution.com/8b02de4bf82d47a7a4a5c6faff6f33e7/',
                'thumbnail'   => 'https://img.gamedistribution.com/8b02de4bf82d47a7a4a5c6faff6f33e7-512x384.jpeg',
                'is_featured' => true,
                'plays'       => 3100,
                'tags'        => ['slope', 'ball', 'reflex'],
            ],
            [
                'title'       => 'World\'s Hardest Game',
                'description' => 'Navigate a red square through waves of blue circles. Deceptively brutal.',
                'category'    => 'adventure',
                'embed_url'   => 'https://html5.gamedistribution.com/5c5b04481e3e46d1bab7d18c09d3a2d2/',
                'thumbnail'   => 'https://img.gamedistribution.com/5c5b04481e3e46d1bab7d18c09d3a2d2-512x384.jpeg',
                'is_featured' => true,
                'plays'       => 2400,
                'tags'        => ['hard', 'dodge', 'classic'],
            ],
            [
                'title'       => 'Vex 5',
                'description' => 'Vault, slide, and wall-run through brutal stickman obstacle courses.',
                'category'    => 'adventure',
                'embed_url'   => 'https://html5.gamedistribution.com/cb58db9ab64d46d7924bd4b1ce04a1c8/',
                'thumbnail'   => 'https://img.gamedistribution.com/cb58db9ab64d46d7924bd4b1ce04a1c8-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 1140,
                'tags'        => ['stickman', 'obstacle', 'platformer'],
            ],
            [
                'title'       => 'Arrow Slide Puzzle',
                'description' => 'Tap arrows to slide them in the direction they point — clear the board to reveal a hidden picture.',
                'category'    => 'adventure',
                'embed_url'   => 'https://html5.gamedistribution.com/b25e864c4aae4d21af2a31ecc01c3759/',
                'thumbnail'   => 'https://img.gamedistribution.com/b25e864c4aae4d21af2a31ecc01c3759-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 870,
                'tags'        => ['puzzle', 'slide', 'logic'],
            ],
            [
                'title'       => 'Cat Simulator',
                'description' => 'Knock things off shelves and cause havoc as an adorable house cat.',
                'category'    => 'adventure',
                'embed_url'   => 'https://html5.gamedistribution.com/405c00612981466cbc5d9dcef4214811/',
                'thumbnail'   => 'https://img.gamedistribution.com/405c00612981466cbc5d9dcef4214811-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 940,
                'tags'        => ['cat', 'sandbox', 'funny'],
            ],

            // ── Multiplayer IO (3) ───────────────────────────────────────────
            [
                'title'       => 'Hole.io',
                'description' => 'Control a black hole that swallows objects and rivals to grow bigger.',
                'category'    => 'multiplayer',
                'embed_url'   => 'https://html5.gamedistribution.com/2b39f5b4de124bdea76e51fd43a24764/',
                'thumbnail'   => 'https://img.gamedistribution.com/2b39f5b4de124bdea76e51fd43a24764-512x384.jpeg',
                'is_featured' => true,
                'plays'       => 2500,
                'tags'        => ['io', 'hole', 'grow'],
            ],

            [
                'title'       => 'HexSweep.io',
                'description' => 'Fight against other players in multiplayer hexagonal minesweeper — claim and steal territory.',
                'category'    => 'multiplayer',
                'embed_url'   => 'https://html5.gamedistribution.com/82994c4d5faf459a98d155169c192092/',
                'thumbnail'   => 'https://img.gamedistribution.com/82994c4d5faf459a98d155169c192092-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 680,
                'tags'        => ['io', 'minesweeper', 'multiplayer'],
            ],



            // ── Strategy (4) — hashes verified from gamedistribution.com search snippets ──
            [
                'title'       => 'Cursed Treasure',
                'description' => 'Play the bad guy — defend your gems from heroes using orcs, undead, and demons in this tower defense classic.',
                'category'    => 'strategy',
                'embed_url'   => 'https://html5.gamedistribution.com/22891cab98224f80a4405f7f0e53c8c1/',
                'thumbnail'   => 'https://img.gamedistribution.com/22891cab98224f80a4405f7f0e53c8c1-512x384.jpeg',
                'is_featured' => true,
                'plays'       => 2600,
                'tags'        => ['tower-defense', 'gems', 'strategy'],
            ],
            [
                'title'       => 'Empire Rush: Rome Wars',
                'description' => 'Defend Rome from barbarian waves by building towers and deploying legions across historic battlefields.',
                'category'    => 'strategy',
                'embed_url'   => 'https://html5.gamedistribution.com/242b8926435f428fb8c4534c8343b7f5/',
                'thumbnail'   => 'https://img.gamedistribution.com/242b8926435f428fb8c4534c8343b7f5-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 1750,
                'tags'        => ['tower-defense', 'rome', 'strategy'],
            ],
            [
                'title'       => 'AOD: Art of Defense',
                'description' => 'Stop enemy waves by placing towers in smart locations. Every move matters in this strategic defense challenge.',
                'category'    => 'strategy',
                'embed_url'   => 'https://html5.gamedistribution.com/941d9c0be5f24d83a1e5ca336f3e6ae4/',
                'thumbnail'   => 'https://img.gamedistribution.com/941d9c0be5f24d83a1e5ca336f3e6ae4-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 1300,
                'tags'        => ['tower-defense', 'strategy', 'waves'],
            ],
            [
                'title'       => 'Stick War: New Age',
                'description' => 'Lead your armed stickman through 40 obstacle-packed episodes. Destroy foes and conquer all challenges.',
                'category'    => 'strategy',
                'embed_url'   => 'https://html5.gamedistribution.com/562cce5513044dfb9de268df27c0ed46/',
                'thumbnail'   => 'https://img.gamedistribution.com/562cce5513044dfb9de268df27c0ed46-512x384.jpeg',
                'is_featured' => false,
                'plays'       => 1550,
                'tags'        => ['stickman', 'action', 'strategy'],
            ],
            [
                'title'         => 'Snow Bros',
                'description' => 'Lead your armed stickman through 40 obstacle-packed episodes. Destroy foes and conquer all challenges.',
                'launch_type'   => 'emulator',
                'emulator_core' => 'arcade',
                'rom_url'       => '/roms/snowbros.zip',
                'thumbnail'     => '/images/thumbnails/snowbros.jpg',
                'embed_url'     => null,
                'external_url'  => null,
                'is_featured'   => true,
                'plays'         => 3800,
                'category'      => 'arcade',
                'tags'          => ['arcade', 'classic', 'retro', 'co-op'],
            ],
            [
                'title'         => 'Tekken 3',
                'description' => 'Lead your armed stickman through 40 obstacle-packed episodes. Destroy foes and conquer all challenges.',
                'launch_type'   => 'emulator',
                'emulator_core' => 'psx',
                'rom_url'       => '/roms/tekken3.zip',
                'thumbnail'     => '/images/thumbnails/tekken3.jpg',
                'embed_url'     => null,
                'external_url'  => null,
                'is_featured'   => true,
                'plays'         => 5100,
                'category'      => 'action',
                'tags'          => ['fighting', 'classic', 'retro'],
            ],
        ];

        foreach ($games as $game) {
            Game::updateOrCreate(
                ['title' => $game['title']],
                $game
            );
        }
    }
}
