<?php

namespace Database\Seeders;

use App\Models\Game;
use Illuminate\Database\Seeder;

class GameSeeder extends Seeder
{
    public function run(): void
    {
        $games = [
            // ── Puzzle ──────────────────────────────────────────────────────
            [
                'title'       => '2048',
                'description' => 'Slide tiles on a grid to combine numbers and reach the 2048 tile. Addictive puzzle game.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://play2048.co/',
                'thumbnail'   => 'https://play2048.co/meta/apple-touch-icon.png',
                'is_featured' => true,
                'plays'       => 1240,
                'tags'        => ['puzzle', 'numbers', 'casual'],
            ],
            [
                'title'       => 'Sudoku',
                'description' => 'Fill the 9×9 grid so every row, column, and box contains digits 1–9.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://sudoku.com/',
                'thumbnail'   => 'https://imgs.crazygames.com/games/sudoku/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 540,
                'tags'        => ['puzzle', 'numbers', 'logic'],
            ],
            [
                'title'       => 'Jigsaw Puzzles',
                'description' => 'Drag and drop pieces to complete beautiful jigsaw puzzles of varying difficulty.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://www.jigsawplanet.com/',
                'thumbnail'   => 'https://imgs.crazygames.com/games/jigsaw-puzzle/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 430,
                'tags'        => ['puzzle', 'jigsaw', 'casual'],
            ],
            [
                'title'       => 'Mahjong',
                'description' => 'Match and remove pairs of tiles to clear the board in this classic solitaire variant.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://www.mahjong.org/',
                'thumbnail'   => 'https://imgs.crazygames.com/games/mahjong-classic/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 390,
                'tags'        => ['mahjong', 'tiles', 'classic'],
            ],
            [
                'title'       => 'Nonograms',
                'description' => 'Use number clues to colour the correct cells and reveal a hidden pixel-art picture.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://www.nonograms.org/',
                'thumbnail'   => 'https://imgs.crazygames.com/games/nonogram/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 210,
                'tags'        => ['nonogram', 'logic', 'pixel'],
            ],
            [
                'title'       => 'Crossword',
                'description' => 'Solve daily crossword puzzles with clues ranging from easy to expert.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://www.nytimes.com/crosswords/game/mini',
                'thumbnail'   => 'https://imgs.crazygames.com/games/crossword/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 670,
                'tags'        => ['crossword', 'words', 'daily'],
            ],
            [
                'title'       => 'Minesweeper',
                'description' => 'Flag all mines without triggering any of them — pure logic under pressure.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://minesweeper.online/',
                'thumbnail'   => 'https://imgs.crazygames.com/games/minesweeper/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 820,
                'tags'        => ['minesweeper', 'classic', 'logic'],
            ],
            [
                'title'       => 'Wordle',
                'description' => 'Guess the five-letter word in six tries. A new word every day.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://www.nytimes.com/games/wordle/index.html',
                'thumbnail'   => 'https://www.nytimes.com/games-assets/v2/metadata/wordle-icon.png',
                'is_featured' => true,
                'plays'       => 2950,
                'tags'        => ['words', 'daily', 'casual'],
            ],
            [
                'title'       => 'Unblock Me',
                'description' => 'Slide blocks out of the way to free the red block from the grid.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://www.crazygames.com/game/unblock-it',
                'thumbnail'   => 'https://imgs.crazygames.com/games/unblock-it/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 310,
                'tags'        => ['sliding', 'logic', 'puzzle'],
            ],
            [
                'title'       => 'Pipe Puzzle',
                'description' => 'Rotate pipe segments to connect the source to the drain without leaks.',
                'category'    => 'puzzle',
                'embed_url'   => 'https://www.crazygames.com/game/pipe-puzzle',
                'thumbnail'   => 'https://imgs.crazygames.com/games/pipe-puzzle/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 185,
                'tags'        => ['pipes', 'rotation', 'logic'],
            ],

            // ── Arcade ──────────────────────────────────────────────────────
            [
                'title'       => 'Tetris',
                'description' => 'The classic block-stacking game. Clear lines before the blocks reach the top.',
                'category'    => 'arcade',
                'embed_url'   => 'https://tetris.com/play-tetris',
                'thumbnail'   => 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Typical_Tetris_Game.svg/400px-Typical_Tetris_Game.svg.png',
                'is_featured' => true,
                'plays'       => 3890,
                'tags'        => ['classic', 'arcade', 'blocks'],
            ],
            [
                'title'       => 'Flappy Bird',
                'description' => 'Tap to keep the bird flying through the pipes. Simple but brutally hard.',
                'category'    => 'arcade',
                'embed_url'   => 'https://flappybird.io/',
                'thumbnail'   => 'https://imgs.crazygames.com/games/flappy-bird/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 876,
                'tags'        => ['bird', 'tap', 'hard'],
            ],
            [
                'title'       => 'Snake',
                'description' => 'Guide the snake to eat food and grow — without hitting the walls or yourself.',
                'category'    => 'arcade',
                'embed_url'   => 'https://playsnake.org/',
                'thumbnail'   => 'https://imgs.crazygames.com/games/snake/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 710,
                'tags'        => ['snake', 'classic', 'retro'],
            ],
            [
                'title'       => 'Pac-Man',
                'description' => 'Chomp dots and dodge ghosts in the iconic golden-age arcade maze.',
                'category'    => 'arcade',
                'embed_url'   => 'https://www.google.com/logos/2010/pacman10-i.html',
                'thumbnail'   => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Pac-Man.svg/400px-Pac-Man.svg.png',
                'is_featured' => true,
                'plays'       => 4200,
                'tags'        => ['pacman', 'maze', 'classic'],
            ],
            [
                'title'       => 'Space Invaders',
                'description' => 'Shoot descending alien waves before they reach the ground.',
                'category'    => 'arcade',
                'embed_url'   => 'https://www.crazygames.com/game/space-invaders',
                'thumbnail'   => 'https://imgs.crazygames.com/games/space-invaders/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 960,
                'tags'        => ['shooter', 'aliens', 'retro'],
            ],
            [
                'title'       => 'Breakout',
                'description' => 'Bounce the ball to smash all the bricks without letting it fall.',
                'category'    => 'arcade',
                'embed_url'   => 'https://www.crazygames.com/game/breakout',
                'thumbnail'   => 'https://imgs.crazygames.com/games/breakout/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 530,
                'tags'        => ['ball', 'bricks', 'classic'],
            ],
            [
                'title'       => 'Dino Run',
                'description' => 'Jump cacti and duck under pterodactyls in Chrome\'s famous offline dinosaur game.',
                'category'    => 'arcade',
                'embed_url'   => 'https://chromedino.com/',
                'thumbnail'   => 'https://chromedino.com/assets/offline-sprite-2x.png',
                'is_featured' => false,
                'plays'       => 1560,
                'tags'        => ['dino', 'runner', 'chrome'],
            ],
            [
                'title'       => 'Geometry Dash',
                'description' => 'Jump and fly your way through rhythm-based obstacle courses.',
                'category'    => 'arcade',
                'embed_url'   => 'https://www.crazygames.com/game/geometry-dash-classic',
                'thumbnail'   => 'https://imgs.crazygames.com/games/geometry-dash-classic/cover_16x9.jpg',
                'is_featured' => true,
                'plays'       => 2780,
                'tags'        => ['rhythm', 'jump', 'hard'],
            ],
            [
                'title'       => 'Galaga',
                'description' => 'Defend Earth against wave after wave of alien bug attackers.',
                'category'    => 'arcade',
                'embed_url'   => 'https://www.crazygames.com/game/galaga',
                'thumbnail'   => 'https://imgs.crazygames.com/games/galaga/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 740,
                'tags'        => ['shooter', 'aliens', 'retro'],
            ],
            [
                'title'       => 'Asteroids',
                'description' => 'Spin, thrust, and shoot to destroy tumbling space rocks.',
                'category'    => 'arcade',
                'embed_url'   => 'https://www.crazygames.com/game/asteroids',
                'thumbnail'   => 'https://imgs.crazygames.com/games/asteroids/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 480,
                'tags'        => ['space', 'shooter', 'retro'],
            ],

            // ── Strategy ────────────────────────────────────────────────────
            [
                'title'       => 'Chess',
                'description' => 'Play chess against an AI or challenge a friend. Multiple difficulty levels.',
                'category'    => 'strategy',
                'embed_url'   => 'https://www.chess.com/play/computer',
                'thumbnail'   => 'https://www.chess.com/bundles/web/images/offline-play/standardboard.png',
                'is_featured' => true,
                'plays'       => 2100,
                'tags'        => ['chess', 'strategy', 'ai'],
            ],
            [
                'title'       => 'Checkers',
                'description' => 'Classic draughts — jump over your opponent\'s pieces to capture them all.',
                'category'    => 'strategy',
                'embed_url'   => 'https://www.crazygames.com/game/checkers',
                'thumbnail'   => 'https://imgs.crazygames.com/games/checkers/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 460,
                'tags'        => ['checkers', 'board', 'classic'],
            ],
            [
                'title'       => 'Reversi / Othello',
                'description' => 'Flip your opponent\'s discs by trapping them between yours.',
                'category'    => 'strategy',
                'embed_url'   => 'https://www.crazygames.com/game/othello',
                'thumbnail'   => 'https://imgs.crazygames.com/games/othello/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 310,
                'tags'        => ['othello', 'discs', 'board'],
            ],
            [
                'title'       => 'Go',
                'description' => 'Surround territory and capture stones in the ancient strategy game of Go.',
                'category'    => 'strategy',
                'embed_url'   => 'https://online-go.com/',
                'thumbnail'   => 'https://cdn.online-go.com/assets/og-default.jpg',
                'is_featured' => false,
                'plays'       => 290,
                'tags'        => ['go', 'board', 'ancient'],
            ],
            [
                'title'       => 'Tower Defense',
                'description' => 'Place towers along the path to stop waves of enemies from reaching your base.',
                'category'    => 'strategy',
                'embed_url'   => 'https://www.crazygames.com/game/tower-defense',
                'thumbnail'   => 'https://imgs.crazygames.com/games/tower-defense/cover_16x9.jpg',
                'is_featured' => true,
                'plays'       => 1850,
                'tags'        => ['tower', 'defense', 'waves'],
            ],
            [
                'title'       => 'Risk-like Wars',
                'description' => 'Conquer territories by deploying armies and rolling dice to battle opponents.',
                'category'    => 'strategy',
                'embed_url'   => 'https://warzone.com/',
                'thumbnail'   => 'https://imgs.crazygames.com/games/warzone/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 680,
                'tags'        => ['war', 'territory', 'dice'],
            ],
            [
                'title'       => 'Battleship',
                'description' => 'Call out coordinates to find and sink your opponent\'s hidden fleet.',
                'category'    => 'strategy',
                'embed_url'   => 'https://www.crazygames.com/game/battleship-online',
                'thumbnail'   => 'https://imgs.crazygames.com/games/battleship-online/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 520,
                'tags'        => ['battleship', 'naval', 'classic'],
            ],
            [
                'title'       => 'Connect Four',
                'description' => 'Drop coloured discs to form four in a row — before your opponent does.',
                'category'    => 'strategy',
                'embed_url'   => 'https://www.crazygames.com/game/connect-four',
                'thumbnail'   => 'https://imgs.crazygames.com/games/connect-four/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 640,
                'tags'        => ['connect4', 'board', 'two-player'],
            ],
            [
                'title'       => 'Hex FRVR',
                'description' => 'Fit hexagonal blocks onto the board and clear full lines and columns.',
                'category'    => 'strategy',
                'embed_url'   => 'https://hex.frvr.com/',
                'thumbnail'   => 'https://frvr.com/static/games/hex/icon.png',
                'is_featured' => false,
                'plays'       => 370,
                'tags'        => ['hex', 'blocks', 'casual'],
            ],
            [
                'title'       => 'Tic-Tac-Toe',
                'description' => 'The timeless three-in-a-row duel, now with an unbeatable AI mode.',
                'category'    => 'strategy',
                'embed_url'   => 'https://www.crazygames.com/game/tic-tac-toe',
                'thumbnail'   => 'https://imgs.crazygames.com/games/tic-tac-toe/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 910,
                'tags'        => ['tictactoe', 'classic', 'casual'],
            ],

            // ── Action ──────────────────────────────────────────────────────
            [
                'title'       => 'Shell Shockers',
                'description' => 'Egg-shaped soldiers battle it out in this quirky first-person shooter.',
                'category'    => 'action',
                'embed_url'   => 'https://shellshock.io/',
                'thumbnail'   => 'https://imgs.crazygames.com/games/shell-shockers/cover_16x9.jpg',
                'is_featured' => true,
                'plays'       => 3200,
                'tags'        => ['fps', 'multiplayer', 'eggs'],
            ],
            [
                'title'       => 'Bullet Force',
                'description' => 'Feature-packed 3-D multiplayer FPS with customisable loadouts and multiple maps.',
                'category'    => 'action',
                'embed_url'   => 'https://www.crazygames.com/game/bullet-force-multiplayer',
                'thumbnail'   => 'https://imgs.crazygames.com/games/bullet-force-multiplayer/cover_16x9.jpg',
                'is_featured' => true,
                'plays'       => 2650,
                'tags'        => ['fps', '3d', 'multiplayer'],
            ],
            [
                'title'       => 'Krunker.io',
                'description' => 'Fast-paced browser FPS with pixel art aesthetics and tons of community maps.',
                'category'    => 'action',
                'embed_url'   => 'https://krunker.io/',
                'thumbnail'   => 'https://imgs.crazygames.com/games/krunker/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 1980,
                'tags'        => ['fps', 'pixel', 'io'],
            ],
            [
                'title'       => 'Zombs Royale',
                'description' => 'Top-down battle royale — outlast 99 other players on a shrinking map.',
                'category'    => 'action',
                'embed_url'   => 'https://zombsroyale.io/',
                'thumbnail'   => 'https://imgs.crazygames.com/games/zombs-royale/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 1430,
                'tags'        => ['battle-royale', 'top-down', 'io'],
            ],
            [
                'title'       => 'Drunken Wrestlers',
                'description' => 'Physics-based ragdoll wrestling — flail your way to victory.',
                'category'    => 'action',
                'embed_url'   => 'https://www.crazygames.com/game/drunken-wrestlers',
                'thumbnail'   => 'https://imgs.crazygames.com/games/drunken-wrestlers/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 870,
                'tags'        => ['physics', 'ragdoll', 'funny'],
            ],
            [
                'title'       => 'Gun Mayhem',
                'description' => 'Blast opponents off the platform in this frantic side-scrolling shooter.',
                'category'    => 'action',
                'embed_url'   => 'https://www.crazygames.com/game/gun-mayhem',
                'thumbnail'   => 'https://imgs.crazygames.com/games/gun-mayhem/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 720,
                'tags'        => ['shooter', 'platform', 'multiplayer'],
            ],
            [
                'title'       => 'Iron Snout',
                'description' => 'Control a pig doing martial-arts combos to smash incoming wolves.',
                'category'    => 'action',
                'embed_url'   => 'https://www.crazygames.com/game/iron-snout',
                'thumbnail'   => 'https://imgs.crazygames.com/games/iron-snout/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 590,
                'tags'        => ['fighting', 'pig', 'funny'],
            ],
            [
                'title'       => 'Superhot',
                'description' => 'Time moves only when you move in this mind-bending FPS puzzle-action game.',
                'category'    => 'action',
                'embed_url'   => 'https://www.crazygames.com/game/superhot',
                'thumbnail'   => 'https://imgs.crazygames.com/games/superhot/cover_16x9.jpg',
                'is_featured' => true,
                'plays'       => 1760,
                'tags'        => ['fps', 'time', 'puzzle'],
            ],
            [
                'title'       => 'Narrow One',
                'description' => 'Team-based archery capture-the-flag inside beautiful castle arenas.',
                'category'    => 'action',
                'embed_url'   => 'https://narrow.one/',
                'thumbnail'   => 'https://narrow.one/res/narrow_one_cover.jpg',
                'is_featured' => false,
                'plays'       => 1120,
                'tags'        => ['archery', 'team', 'castle'],
            ],
            [
                'title'       => 'Stickman Hook',
                'description' => 'Swing through levels on a grappling hook in this physics platformer.',
                'category'    => 'action',
                'embed_url'   => 'https://www.crazygames.com/game/stickman-hook',
                'thumbnail'   => 'https://imgs.crazygames.com/games/stickman-hook/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 940,
                'tags'        => ['stickman', 'swing', 'physics'],
            ],

            // ── Racing ──────────────────────────────────────────────────────
            [
                'title'       => 'Madalin Stunt Cars 2',
                'description' => 'Choose from dozens of supercars and pull off wild stunts on massive tracks.',
                'category'    => 'racing',
                'embed_url'   => 'https://www.crazygames.com/game/madalin-stunt-cars-2',
                'thumbnail'   => 'https://imgs.crazygames.com/games/madalin-stunt-cars-2/cover_16x9.jpg',
                'is_featured' => true,
                'plays'       => 2340,
                'tags'        => ['cars', 'stunts', '3d'],
            ],
            [
                'title'       => 'Drift Hunters',
                'description' => 'Earn points by drifting tuned cars around technical courses.',
                'category'    => 'racing',
                'embed_url'   => 'https://www.crazygames.com/game/drift-hunters',
                'thumbnail'   => 'https://imgs.crazygames.com/games/drift-hunters/cover_16x9.jpg',
                'is_featured' => true,
                'plays'       => 1980,
                'tags'        => ['drift', 'cars', 'tuning'],
            ],
            [
                'title'       => 'Road Rush Cars',
                'description' => 'Dodge oncoming traffic at high speed across multiple highways.',
                'category'    => 'racing',
                'embed_url'   => 'https://www.crazygames.com/game/road-rush-cars',
                'thumbnail'   => 'https://imgs.crazygames.com/games/road-rush-cars/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 670,
                'tags'        => ['traffic', 'speed', 'endless'],
            ],
            [
                'title'       => 'Moto X3M',
                'description' => 'Race a dirt bike through wild obstacle courses full of explosions and loops.',
                'category'    => 'racing',
                'embed_url'   => 'https://www.crazygames.com/game/moto-x3m',
                'thumbnail'   => 'https://imgs.crazygames.com/games/moto-x3m/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 1560,
                'tags'        => ['bike', 'stunts', 'obstacles'],
            ],
            [
                'title'       => 'Formula Rush',
                'description' => 'Top-down F1-style racing — overtake rivals and manage tyre wear.',
                'category'    => 'racing',
                'embed_url'   => 'https://www.crazygames.com/game/formula-rush',
                'thumbnail'   => 'https://imgs.crazygames.com/games/formula-rush/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 430,
                'tags'        => ['f1', 'top-down', 'speed'],
            ],
            [
                'title'       => 'Burnout Drift',
                'description' => 'Smoke the tyres and drift through open sandboxes or timed courses.',
                'category'    => 'racing',
                'embed_url'   => 'https://www.crazygames.com/game/burnout-drift-seaport',
                'thumbnail'   => 'https://imgs.crazygames.com/games/burnout-drift-seaport/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 810,
                'tags'        => ['drift', 'burnout', 'sandbox'],
            ],
            [
                'title'       => 'Bike Racing',
                'description' => 'Wheelie and boost your motorbike to the finish line on bumpy tracks.',
                'category'    => 'racing',
                'embed_url'   => 'https://www.crazygames.com/game/bike-racing',
                'thumbnail'   => 'https://imgs.crazygames.com/games/bike-racing/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 520,
                'tags'        => ['bike', 'wheelie', '2d'],
            ],
            [
                'title'       => 'Traffic Jam 3D',
                'description' => 'Weave through packed highways without crashing in hypnotic 3-D traffic.',
                'category'    => 'racing',
                'embed_url'   => 'https://www.crazygames.com/game/traffic-jam-3d',
                'thumbnail'   => 'https://imgs.crazygames.com/games/traffic-jam-3d/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 640,
                'tags'        => ['traffic', '3d', 'endless'],
            ],

            // ── Sports ──────────────────────────────────────────────────────
            [
                'title'       => 'Head Ball 2',
                'description' => '1-v-1 soccer with oversized heads — score before the clock runs out.',
                'category'    => 'sports',
                'embed_url'   => 'https://www.crazygames.com/game/head-soccer',
                'thumbnail'   => 'https://imgs.crazygames.com/games/head-soccer/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 1100,
                'tags'        => ['soccer', 'heads', 'two-player'],
            ],
            [
                'title'       => 'Basketball Stars',
                'description' => 'Show off ball-handling tricks and score slick buckets in this arcade basketball game.',
                'category'    => 'sports',
                'embed_url'   => 'https://www.crazygames.com/game/basketball-stars',
                'thumbnail'   => 'https://imgs.crazygames.com/games/basketball-stars/cover_16x9.jpg',
                'is_featured' => true,
                'plays'       => 1870,
                'tags'        => ['basketball', 'tricks', 'arcade'],
            ],
            [
                'title'       => 'Ping Pong',
                'description' => 'Reflex-testing table tennis against progressively faster AI opponents.',
                'category'    => 'sports',
                'embed_url'   => 'https://www.crazygames.com/game/ping-pong',
                'thumbnail'   => 'https://imgs.crazygames.com/games/ping-pong/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 490,
                'tags'        => ['ping-pong', 'reflex', 'classic'],
            ],
            [
                'title'       => 'Mini Golf',
                'description' => 'Sink the ball in as few shots as possible on quirky obstacle-filled holes.',
                'category'    => 'sports',
                'embed_url'   => 'https://www.crazygames.com/game/golf-orbit',
                'thumbnail'   => 'https://imgs.crazygames.com/games/golf-orbit/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 760,
                'tags'        => ['golf', 'mini', 'casual'],
            ],
            [
                'title'       => 'Penalty Shooters 2',
                'description' => 'Take and save penalties across a tournament bracket to lift the trophy.',
                'category'    => 'sports',
                'embed_url'   => 'https://www.crazygames.com/game/penalty-shooters-2',
                'thumbnail'   => 'https://imgs.crazygames.com/games/penalty-shooters-2/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 930,
                'tags'        => ['soccer', 'penalty', 'tournament'],
            ],
            [
                'title'       => 'Volley Random',
                'description' => 'Absurd ragdoll volleyball with random terrain every round.',
                'category'    => 'sports',
                'embed_url'   => 'https://www.crazygames.com/game/volley-random',
                'thumbnail'   => 'https://imgs.crazygames.com/games/volley-random/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 580,
                'tags'        => ['volleyball', 'ragdoll', 'funny'],
            ],
            [
                'title'       => 'Darts',
                'description' => 'Aim and throw darts at the board — compete in 301 or cricket modes.',
                'category'    => 'sports',
                'embed_url'   => 'https://www.crazygames.com/game/darts',
                'thumbnail'   => 'https://imgs.crazygames.com/games/darts/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 340,
                'tags'        => ['darts', 'aim', 'casual'],
            ],

            // ── Adventure ───────────────────────────────────────────────────
            [
                'title'       => 'Fireboy and Watergirl',
                'description' => 'Co-op puzzle platformer — use each character\'s element to unlock new paths.',
                'category'    => 'adventure',
                'embed_url'   => 'https://www.crazygames.com/game/fireboy-and-watergirl-1-in-the-forest-temple',
                'thumbnail'   => 'https://imgs.crazygames.com/games/fireboy-and-watergirl-1-in-the-forest-temple/cover_16x9.jpg',
                'is_featured' => true,
                'plays'       => 3050,
                'tags'        => ['co-op', 'puzzle', 'platformer'],
            ],
            [
                'title'       => 'Run 3',
                'description' => 'Sprint through tunnels in space, rotating the tube to avoid gaps.',
                'category'    => 'adventure',
                'embed_url'   => 'https://www.coolmathgames.com/0-run-3',
                'thumbnail'   => 'https://imgs.crazygames.com/games/run-3/cover_16x9.jpg',
                'is_featured' => true,
                'plays'       => 2870,
                'tags'        => ['runner', 'space', 'endless'],
            ],
            [
                'title'       => 'Minecraft Classic',
                'description' => 'Build anything you can imagine with blocks in the original browser version.',
                'category'    => 'adventure',
                'embed_url'   => 'https://classic.minecraft.net/',
                'thumbnail'   => 'https://www.minecraft.net/content/dam/games/minecraft/key-art/MC_The-Wild-Update_540x300.jpg',
                'is_featured' => true,
                'plays'       => 4100,
                'tags'        => ['minecraft', 'building', 'sandbox'],
            ],
            [
                'title'       => 'Vex 5',
                'description' => 'Vault, slide, and wall-run through brutal stickman obstacle courses.',
                'category'    => 'adventure',
                'embed_url'   => 'https://www.crazygames.com/game/vex-5',
                'thumbnail'   => 'https://imgs.crazygames.com/games/vex-5/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 1140,
                'tags'        => ['stickman', 'obstacle', 'platformer'],
            ],
            [
                'title'       => 'Temple Run',
                'description' => 'Swipe to turn, jump, and slide while escaping demon monkeys in an ancient temple.',
                'category'    => 'adventure',
                'embed_url'   => 'https://www.crazygames.com/game/temple-run-2',
                'thumbnail'   => 'https://imgs.crazygames.com/games/temple-run-2/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 1890,
                'tags'        => ['runner', 'temple', 'endless'],
            ],
            [
                'title'       => 'Adventure Story',
                'description' => 'Side-scrolling RPG adventure with swords, magic, and boss fights.',
                'category'    => 'adventure',
                'embed_url'   => 'https://www.crazygames.com/game/adventure-story',
                'thumbnail'   => 'https://imgs.crazygames.com/games/adventure-story/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 760,
                'tags'        => ['rpg', 'side-scroller', 'swords'],
            ],
            [
                'title'       => 'Escape Room',
                'description' => 'Examine every corner of the room, find clues, and escape before time runs out.',
                'category'    => 'adventure',
                'embed_url'   => 'https://www.crazygames.com/game/escape-room',
                'thumbnail'   => 'https://imgs.crazygames.com/games/escape-room/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 620,
                'tags'        => ['escape', 'point-and-click', 'mystery'],
            ],

            // ── Multiplayer IO ───────────────────────────────────────────────
            [
                'title'       => 'Agar.io',
                'description' => 'Grow your cell by eating smaller players and pellets. Avoid bigger ones.',
                'category'    => 'multiplayer',
                'embed_url'   => 'https://agar.io/',
                'thumbnail'   => 'https://imgs.crazygames.com/games/agar-io/cover_16x9.jpg',
                'is_featured' => true,
                'plays'       => 3700,
                'tags'        => ['io', 'cells', 'grow'],
            ],
            [
                'title'       => 'Slither.io',
                'description' => 'Control a snake, eat glowing orbs, and make rivals crash into you.',
                'category'    => 'multiplayer',
                'embed_url'   => 'https://slither.io/',
                'thumbnail'   => 'https://imgs.crazygames.com/games/slither-io/cover_16x9.jpg',
                'is_featured' => true,
                'plays'       => 3450,
                'tags'        => ['io', 'snake', 'multiplayer'],
            ],
            [
                'title'       => 'Skribbl.io',
                'description' => 'Draw a word and guess what others are drawing in this online Pictionary.',
                'category'    => 'multiplayer',
                'embed_url'   => 'https://skribbl.io/',
                'thumbnail'   => 'https://skribbl.io/img/logo.webp',
                'is_featured' => true,
                'plays'       => 2890,
                'tags'        => ['drawing', 'guessing', 'party'],
            ],
            [
                'title'       => 'Diep.io',
                'description' => 'Upgrade your tank, destroy shapes and enemy tanks, and dominate the arena.',
                'category'    => 'multiplayer',
                'embed_url'   => 'https://diep.io/',
                'thumbnail'   => 'https://imgs.crazygames.com/games/diep-io/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 1600,
                'tags'        => ['io', 'tank', 'upgrade'],
            ],
            [
                'title'       => 'Wormate.io',
                'description' => 'Eat sweets to grow your worm and outmanoeuvre opponents in colourful arenas.',
                'category'    => 'multiplayer',
                'embed_url'   => 'https://wormate.io/',
                'thumbnail'   => 'https://imgs.crazygames.com/games/wormate-io/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 1050,
                'tags'        => ['io', 'worm', 'food'],
            ],
            [
                'title'       => 'Paper.io 2',
                'description' => 'Expand your territory by drawing loops — without getting cut off by rivals.',
                'category'    => 'multiplayer',
                'embed_url'   => 'https://paper-io.com/',
                'thumbnail'   => 'https://imgs.crazygames.com/games/paper-io-2/cover_16x9.jpg',
                'is_featured' => false,
                'plays'       => 1280,
                'tags'        => ['io', 'territory', 'paper'],
            ],
            [
                'title'       => 'Drawasaurus',
                'description' => 'Compete to draw words fastest and rack up the most points across multiple rounds.',
                'category'    => 'multiplayer',
                'embed_url'   => 'https://www.drawasaurus.org/',
                'thumbnail'   => 'https://www.drawasaurus.org/img/logo.png',
                'is_featured' => false,
                'plays'       => 830,
                'tags'        => ['drawing', 'guessing', 'party'],
            ],
            [
                'title'       => 'Gartic Phone',
                'description' => 'Alternate between drawing and guessing in this hilarious telephone-game twist.',
                'category'    => 'multiplayer',
                'embed_url'   => 'https://garticphone.com/',
                'thumbnail'   => 'https://garticphone.com/images/og.jpg',
                'is_featured' => true,
                'plays'       => 2200,
                'tags'        => ['drawing', 'party', 'funny'],
            ],
        ];

        foreach ($games as $game) {
            Game::updateOrCreate(
                ['title' => $game['title']],
                $game
            );
        }
    }
}